FROM tiangolo/uvicorn-gunicorn:python3.11

WORKDIR /app


COPY ./requirements.txt ./requirements.txt

ENV VIRTUAL_ENV=/usr/local
RUN pip install uv
RUN uv pip install -r requirements.txt

ADD "https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h" skipcache
RUN uv pip install shrillecho --upgrade

RUN apt-get -y update && apt-get -y install libgl1

COPY ./ ./

CMD ["uvicorn", "server:app", "--proxy-headers", "--log-level", "debug", "--host", "0.0.0.0", "--port", "8001", "--reload"]